version: '3'

services:
  web:
    container_name: users
    build: .
    image: users:latest
    command: python3 app.py
    restart: always
    environment:
    - TEAM_NAME=CC_1665_1725_0201_1608
    ports:
      - "8000:80"
